In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
dataset=pd.read_csv("50_Startups.csv")


In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)


In [4]:
indep=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]


In [5]:
dep=dataset[['Profit']]


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)


In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','linear','sigmoid'], 'C':[100,1000,3000]}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [100, 1000, 3000],
                         'kernel': ['rbf', 'poly', 'linear', 'sigmoid']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_Score Value for best parameters{}:".format(grid.best_params_))


The R_Score Value for best parameters{'C': 3000, 'kernel': 'linear'}:


In [10]:
grid_pred=grid.predict(x_test)
grid_pred

array([115673.87647498, 128415.94769168, 134139.70392095,  76533.90780978,
       177828.31144355, 121408.65126852,  66044.76366321, 101986.10671106,
       122216.61194915, 166059.72361024, 101096.22854208,  87681.97413083,
       116288.07091912, 101125.97457667, 132044.43860775, 164786.76670359,
       155615.95152539])

In [11]:
table=pd.DataFrame.from_dict(re)


In [12]:
filename1="finalized_input_prepro X only-SVM.sav"

pickle.dump(sc,open(filename1,'wb'))

In [13]:
input=pickle.load(open("finalized_input_prepro X only-SVM.sav",'rb'))

In [14]:

filename="finalized_50_Startups_prepro X only-SVM.sav"
pickle.dump(grid,open(filename,'wb'))


In [15]:
loaded_model=pickle.load(open("finalized_50_Startups_prepro X only-SVM.sav",'rb'))

In [16]:
preinput=sc.transform([[1300,12000,4000,0,1]])
preinput

C:\Users\PC\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[-1.41240431, -4.30496048, -1.44694752, -0.42257713,  1.24034735]])

In [17]:
result=loaded_model.predict(preinput)
result

array([33120.66285984])