In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
dataset=pd.read_csv("50_Startups.csv")


In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
indep=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dep=dataset[['Profit']]


In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
x_train=scx.fit_transform(x_train)
x_test=scx.transform(x_test)

In [6]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)


In [7]:
x_train,x_test,y_train,y_test

(array([[-1.41859108,  0.08007161, -1.46280061, -0.42257713,  1.24034735],
        [-1.42804718, -2.75105709, -1.4772005 , -0.42257713,  1.24034735],
        [-0.08524282,  1.20920221, -0.66688679, -0.42257713,  1.24034735],
        [ 0.92434855,  0.02000827,  0.50267699, -0.42257713,  1.24034735],
        [-0.15976805, -0.25272669, -0.7879527 ,  2.36643191, -0.80622577],
        [-0.13057752,  0.27816764, -1.12864651, -0.42257713, -0.80622577],
        [ 0.17083067, -0.01984459,  0.52211324, -0.42257713, -0.80622577],
        [-0.95132351, -1.01325988, -0.357832  , -0.42257713, -0.80622577],
        [ 0.13452258, -0.3220869 ,  0.78167175, -0.42257713, -0.80622577],
        [-1.11922093,  0.20633131, -1.2084469 , -0.42257713,  1.24034735],
        [ 1.04856916,  1.04056545,  0.87960683, -0.42257713,  1.24034735],
        [ 0.45934048,  0.52352964,  0.433766  , -0.42257713, -0.80622577],
        [-0.1046588 ,  0.68219546, -0.43375555, -0.42257713, -0.80622577],
        [ 1.2824925 , -0.

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','linear','sigmoid'], 'C':[100,1000,3000]}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [100, 1000, 3000],
                         'kernel': ['rbf', 'poly', 'linear', 'sigmoid']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_Score Value for best parameters{}:".format(grid.best_params_))

The R_Score Value for best parameters{'C': 3000, 'kernel': 'linear'}:


In [10]:
grid_pred=grid.predict(x_test)
grid_pred

array([ 0.03149282,  0.59565863,  0.7309895 , -0.71536796,  1.78864603,
        0.09980322, -0.99227474, -0.22253061,  0.24236495,  1.54938307,
       -0.15967014, -0.48487405,  0.19719718, -0.42111484,  0.57110189,
        1.33035569,  1.10710435])

In [11]:
table=pd.DataFrame.from_dict(re)


In [12]:
filename1="finalized_input_prepro both-SVM.sav"
pickle.dump(scx,open(filename1,'wb'))

In [13]:
filename2="finalized_output_prepro both-SVM.sav"
pickle.dump(scy,open(filename2,'wb'))

In [14]:
input=pickle.load(open("finalized_input_prepro both-SVM.sav",'rb'))

In [15]:
output=pickle.load(open("finalized_output_prepro both-SVM.sav",'rb'))

In [16]:
filename="finalized_50_Startups_prepro X only-SVM.sav"
pickle.dump(grid,open(filename,'wb'))

In [17]:
loaded_model=pickle.load(open("finalized_50_Startups_prepro X only-SVM.sav",'rb'))

In [18]:
preinput=scx.transform([[1300,12000,4000,0,1]])
preinput

C:\Users\PC\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[-1.41240431, -4.30496048, -1.44694752, -0.42257713,  1.24034735]])

In [19]:
result=loaded_model.predict(preinput)
result

array([-1.46217782])

In [20]:
preoutput=scy.inverse_transform([result])
preoutput

array([[44768.9770621]])